"anthropic_version": "bedrock-2023-05-31"
"max_tokens": 1000
"system": "Respond only in Japanese"
"messages":  [
    {
        "role": "user",
        "content": [{"type": "text", "text": "{prompt}"}]
    }
]
"modelId": "anthropic.claude-3-haiku-20240307-v1:0"
# "modelId": "anthropic.claude-3-sonnet-20240229-v1:0"
# "modelId": "anthropic.claude-3-opus-20240229-v1:0"

"query": "What is Amazon doing in the field of generative AI?"
